### PR TITLE
Fixes #491 - mainUrl was not an absolute path

### LINKED ISSUE #491: Updating to 12.2.2 returns a script error
**Describe the bug**
I updated the package to 12.2.2 and now elfinder is no longer working.

There is a script error and when looking at the missing js files, the package tries to load them from `elfinder/bundles/fmelfinder/...` instead of `public/bundles/fmelfinder/...`

Reverting to 12.2.1 seems to fix this issue.
I don't understand what can be causing it.

Screenshot_20230209_121318

Screenshot_20230209_121336

### PR DESCRIPTION
**Pull request by UlrichHP**
Following issue #491, in **ElFinderController**, when defining **$mainUrl** at line 229, this is a relative path and not absolute.
To make it absolute, a **/** have been added according to the [Symfony documentation](https://symfony.com/doc/current/components/asset.html#usage).

### CODE REVIEW

File: src/Controller/ElFinderController.php [hunk 1]
```diff
@@ -226,7 +226,7 @@ public function mainJS()
     {
         $version = new EmptyVersionStrategy();
         $package = new Package($version);
-        $mainUrl = $package->getUrl('bundles/fmelfinder/js');
+        $mainUrl = $package->getUrl('/bundles/fmelfinder/js');
```
Comment (johanadivare) [inline src/Controller/ElFinderController.php:229]: I know this is already merged but shouldn't this code also contain the `assets_path`? see example config https://github.com/helios-ag/FMElfinderBundle#add-configuration-options-to-your-configyaml where we can define a asset path?

Comment (johanadivare) [reply src/Controller/ElFinderController.php:229]: I just confirmed for me when having `assets_path` set and chaning this line to:
```
        $mainUrl = $package->getUrl(sprintf('%s/bundles/fmelfinder/js', $this->params['assets_path']));
```
I loads my assets file for elfinder again
